# Maintainer: Tung Vu <vutung2311 at gmail dot com>

# The driver sources in this directory are generated by sync-upstream.sh from
# the linux-ntfs submodule plus patches/*.patch. Run it after updating the
# submodule; it rewrites the upstream file list, pkgver and checksums below.

_pkgname=ntfsplus
pkgname=$_pkgname-dkms
_upstream_commit=d7fb9077b24e2e01df437b0b7f01d25c98301409
pkgver=1.0.20260921.013456.gd7fb907
pkgrel=1
pkgdesc='NTFS+ filesystem driver with write support using iomap (DKMS module for kernel 6.18+)'
arch=('any')
url='https://github.com/namjaejeon/linux-ntfs'
license=('GPL-2.0-only')
depends=('dkms')
conflicts=('ntfsplus')

# Owned by this packaging repo
_buildfiles=(dkms.conf.in Makefile find-objtool.sh)
# BEGIN upstream sources (generated by sync-upstream.sh, do not edit)
_upstream=(
          aops.c
          aops.h
          attrib.c
          attrib.h
          attrlist.c
          attrlist.h
          bdev-io.c
          bitmap.c
          bitmap.h
          collate.c
          collate.h
          compress.c
          debug.c
          debug.h
          decompress_common.c
          decompress_common.h
          dir.c
          dir.h
          ea.c
          ea.h
          file.c
          index.c
          index.h
          inode.c
          inode.h
          iomap.c
          iomap.h
          Kconfig
          layout.h
          lcnalloc.c
          lcnalloc.h
          lib.h
          logfile.c
          logfile.h
          lzx_decompress.c
          mft.c
          mft.h
          mst.c
          namei.c
          ntfs_codec.h
          ntfs.h
          object_id.c
          object_id.h
          reparse.c
          reparse.h
          runlist.c
          runlist.h
          super.c
          sysctl.c
          sysctl.h
          time.h
          uapi_ntfs.h
          unistr.c
          upcase.c
          volume.h
          wof.c
          xpress_decompress.c
)
# END upstream sources
source=("${_buildfiles[@]}" "${_upstream[@]}")
sha256sums=('d91641eca39057e8838f1f8f387f83d88a094dd170df4c1cbe9b345afe28640c'
            '4b092edc62e425aecad55edaca1ee1cf28832d9ffeac01d1215ec6fa200c50d6'
            'be2a461d87cd94227b6f84f4f061d778e44dfcf296f957a11518d9c6a18ff4b9'
            'e95136824a40d2c1a8f8c1e7409d28b917aef1b8849a959549af4d34d4adf19d'
            '3a9e11588d3350a27ed7166d458aa19ac46fd4b677f818474728859d4c9ca3c9'
            '03c55db301d13d819eafc12bc6af6a1cf4347e524c163d1d92b0e82567037543'
            '6c86d9b046795210c205692eaf7d3a178143d68ac3f6579940ece2cff3d307d6'
            '5b93c340baf5d5e6e73a6bc8a869901690fc2ab34337957d68728c566997af30'
            '0473b67f29374b811d98c8a5cdc761e761e591f56ae3f75c30c3ae0bfaaa619f'
            'ada88c7f82c491b3a20cb0dfd1ccdad8d6b6136bb33f9da6ff0d5050093b38e0'
            'd4f37a9634a9271a7e6adbbbb14c8ce0dde504d5749141a803954636fa5985be'
            'f8f5bb9b5e4dee9df9b471b2ee4d1589cb00481f05c3a98d2d46ab327a790e92'
            'ad6020229222175c0d71e743afbdc8c8f579d41425fd67ad382c394327b0d89d'
            '15a2a9ebdf934016c1c72ec747441612e8ea86ce97176c6a560304f30e1485ef'
            '3bb716724dac87b9302bcb6cc9d8937e18bc488d5bfaa634fe5f4f6111f54028'
            'fa9a92cfdb8f47c3cc5244131acaa19a0d8ff3ffa21e04fa5a71237817229988'
            '14a3fec37e0f2d63e6b686c8cd4a272f6b67a0b7f10b6a4ab39493666df72e3b'
            '01f6b2f3b20c69fea541fe1e4798ee8ea17d02d63e8bac0c10adf5434977446d'
            'c1d3f3adae3e03274111ad2b3302fa25e083d0314cbeda8b60b2d66cae93833b'
            'addb2f28f1c9899a9d1786a54eb96ad0b262ffc35c6c0c58595e22a55ee5003c'
            '6896c79e07b486f9051dafa2186c0cf283739496e9c5573c78f5b74c3da1dc71'
            'b876edf6b5779d1074586e2df6a658038456f30a74ad93da8bf4a332d335d1e9'
            '0f75cb7ebff35a747f62d0cd9592af6de041f01c39434beac81dce4c05f7222f'
            '6ca1c54c41dc26326718a9d5f92a255792ab1f734c5aaff16da8ecb1bd75d0b5'
            '24b561b2ff31c76965408c2f9ea76a08f70e38b8302abec02303e8ee794e4e1f'
            'a9926e4192dcb6cfc80eae3023715fd3722fa4db4d966454b80798c56573b7fc'
            '63b8d39fbdb553aa13565167caa09bb7e60bc559e510f14ec5407495f382d402'
            'a305a694d200063081e1e5c927fa63e48f5a3c981a97ebadca7f4ebd5c4cf34a'
            '8edd2b3e150f0dfcad5ccc8d32e0ae991f7ad3d4464134fe66c4e27e48d560ea'
            'c9469e0bc7cd370db3a10298b527f59b693a2441d63dd1d3176968a810dd991c'
            'd69a856af3ee070c67931349f68592f8313647470ee2495332bf02a508caddd1'
            'd708494cadfc769ca5d7cd651d6bad170262803aab2cafe41a5228c042cbfe58'
            '01f1a3baf27ba67be3b7f7bfd364afe156147ed3fe11acbbcfd3e9a7b446f720'
            'a5ed692bada562110ac4886d857f5f68d35d7c72fe9e5a8cfb32f6441ea30458'
            '83acad9ce4759fd545398c74471011dab34a4c9d9f0c90db8b460024fde03d5c'
            'ec0c6495efa57edc7e561431f296e9c85048c6bf520df76ca0c4af18c9786b97'
            'bd8b6e360f466f2acaaea2bfc59ca5741dcd35698d676a22cc2e3fac9a950a6d'
            'e31167624a50d7094365f32a27f2edce22ccecf861fd0e17861ac4676322be30'
            '69ed62d4f9ed41036b6fd1afb54fbea543b26f36f8148d454d33366e63ba86e2'
            '88c474bba619a16bca0f163a0cdbdd0ff2f8432cb93eb6b8bedf7e396d634743'
            'ae83aea04ea7085f586622292e148651ceeefaed800b8201ee04e0b2aa1d81e2'
            '81bc49583d36206f17f53f7e3c997f211b9f5dabe7f38528eab5c3f6fb610ea2'
            '52b69e6676a12394583bd7e1079c73a0ac2f4e55040e4c3ccdc428024b80cfa9'
            '5be22a305ddf2e38d2bdffc7c64688ea0943a6c6a5bb75fdb0f5d6a3f4923a3f'
            '84bb3475d914daf45c58a34509ce3e8bc5d539051232c1bcbca384ef2cb58f6f'
            '51701cdbbe34b2f8debca747f40fec9b3c9f435305c4dad8b44930e40b6c43d0'
            '823c8f83277597ffaf782d977e4cc271bd5a33ce22b2dcd75412693d051d39c6'
            '9527ef9ac5d4d60f94a42d6db21b60a605f968a75023093df6e75ce78ccf7f64'
            '8fab54ec273fb5482eda362a0c9605a6da6a2e252c3ca8f60864d950377a268f'
            '69fff40b696705b6f48d7a648b4fd9eb3a2f9820c7d63dbfcd38e332d295625a'
            'f66870377f7828afdbab7e8a7583814e80140b496eadc43a81c025852aff7c93'
            '09fd17abfb901176614f41b1c23ef8132eb087e120885f931670c3c5e9dbcd20'
            '295a96c9bf8bf4917a8adc9b846a0b3986b51f3f6c154fc14ca12277df578744'
            'ff68228a1839f51581bde615f47cd12e268144eb5345b52986ada9f83b34f7e6'
            '5f63d04bd17f0f99ef8247a0a0961a96005dfbce81cce9ab29f9a4d76f206c9e'
            '99706e632ecff0036e327b33c6c4a29235712c83960a39e7c4ef3aad4ed99bdb'
            '2e4de2ac978f905492dd505e938b949285251e1ec6dbff9da59002a4d7c86184'
            '44123757f5040eff9bc86b46c31b6b93962e4e64179bbce26fd7a5bff00779c9'
            'faa579bfe66744821216025a12de4b5332ea6bd314e199459ca2ef690b88ca6c'
            '32d95549d820f9b5020850803eff19cc26801497912d8c38a33ede5b33d18ab7')

package() {
  local dest="$pkgdir/usr/src/$_pkgname-$pkgver" f

  for f in "${source[@]}"; do
    install -Dm644 "$srcdir/$f" "$dest/$f"
  done
  chmod 755 "$dest/find-objtool.sh"

  mv "$dest/dkms.conf.in" "$dest/dkms.conf"
  sed -i "s/@VERSION@/$pkgver/" "$dest/dkms.conf"
}
